name: shopos
description: POS and accounts ledger.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  audioplayers: ^0.20.1
  cached_network_image: ^3.2.1
  cookie_jar: ^3.0.1
  date_time_picker: ^2.1.0
  dio: ^4.0.6
  dio_cookie_manager: ^2.0.0
  firebase_auth: ^3.3.18
  firebase_core: ^1.17.0
  flutter:
    sdk: flutter
  flutter_barcode_scanner: ^2.0.0
  flutter_bloc: ^8.0.1
  flutter_html_to_pdf: ^0.7.0
  flutter_localizations:
    sdk: flutter
  # flutter_secure_storage: ^5.0.2
  flutter_typeahead: ^3.2.5
  flutter_vibrate: ^1.3.0
  get_it: ^7.2.0
  image_picker: ^0.8.5+3
  in_app_update: ^3.0.0
  intl: ^0.17.0
  open_file: ^3.2.1
  path_provider: ^2.0.9
  pdf: ^3.7.4
  permission_handler: ^9.2.0
  pin_code_fields: ^7.4.0
  share_plus: ^4.0.4
  slidable_button: ^1.3.1
  whatsapp_share2: ^2.0.2
  rflutter_alert: ^2.0.4
  flutter_svg: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"
  flutter_lints: ^1.0.0
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/audio/
    - assets/icon/
  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/CustomIcons.ttf
